### ISSUE TITLE
Could not load file; FileLoadException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [santiagomoreta/tesseractdotnet#13]
```
What steps will reproduce the problem?
1. Checked out the project via svn (svn co 
https://tesseractdotnet.googlecode.com/svn/trunk/dotnetwrapper)
2. Opened in Visual Studio 2010
3. Hit F5 to load the error, running it while not in debug simply closes down 
the program

What is the expected output? What do you see instead?
I expected the form application to load, instead it simply closes


What version of the product are you using? On what operating system?
Revision 48, Windows 7, on Visual Studio 2010


Please provide any additional information below.
Just downloaded the project today and figured I'd play around with it and see 
what results I get. However, when I'm trying to run the project I get the below 
error:

Could not load file or assembly 'tesseractengine3, Version=0.0.0.0, 
Culture=neutral, PublicKeyToken=null' or one of its dependencies. The 
application has failed to start because its side-by-side configuration is 
incorrect. Please see the application event log or use the command-line 
sxstrace.exe tool for more detail. (Exception from HRESULT: 0x800736B1)
   at Tesseract.OCR.AppEntry.MainForm..ctor()
   at Tesseract.OCR.AppEntry.Program.Main() in C:\Users\Guest\Desktop\dotnetwrapper\TesseractBasedOCRAnalysis\Tesseract.OCR.AppEntry\Program.cs:line 36

Line 36 refers to the new MainForm I found, but the actual error break occurs 
on line 21 in the Main.Form.Designer.cs where this.end() is called. I feel that 
my issue is simple since I haven't seen it on the forums. Anyway, thanks for 
any help :D

```

Original issue reported on code.google.com by `Vehix...@gmail.com` on 9 Aug 2011 at 8:29

**Comment by GoogleCodeExporter** [comment]
```
Someone pointed out the Wiki, trying that out now currently

```

Original comment by `Vehix...@gmail.com` on 9 Aug 2011 at 8:34

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hello everybody! Can you help me to resolve the below problem?
1. How to do pre-processing image (such as Binarization, Noise Detection & 
Reduction, Skew & orientation detection...) (use source code tesseract ocr 
3.01) ?
2. How to do "page layout analysis" combine with recognize characters (use 
source code tesseract ocr 3.01)?
Thank you very much.
```

Original comment by `phamphih...@gmail.com` on 11 Aug 2011 at 1:24

**Comment by GoogleCodeExporter** [comment]
```
Hi Vehix, I am having the same problem, how did you solve it?
```

Original comment by `ccbaci` on 3 Jun 2013 at 7:00

**Comment by GoogleCodeExporter** [comment]
```
Please update the status on above query. I have stuck on same point.
```

Original comment by `globalwo...@gmail.com` on 7 Jun 2013 at 10:40

**Comment by GoogleCodeExporter** [comment]
```
Hi, I have same issue , anyone got solution ?
```

Original comment by `rsoni1...@gmail.com` on 6 May 2015 at 11:34
